/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.bitspire.meetup.pulsar;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;

public class App {

    public static void main(String[] args) {

        String url = "pulsar://localhost:6650";
        String topic = "persistent://public/default/hello-topic";

        try (PulsarClient client = PulsarClient.builder().serviceUrl(url).build()) {

            try (Producer<byte[]> producer = client.newProducer().topic(topic).create()) {
                for (int i = 1; i <= 10; i++) {
                    producer.send(String.format("[%02d] %s", i, "Pulsar Rocks!").getBytes());
                }

            } catch (PulsarClientException e) {
                System.err.println("Cannot create producer");
                e.printStackTrace();
            }
        } catch (PulsarClientException e) {
            System.err.println("Cannot connect to Pulsar cluster");
            e.printStackTrace();
        }
    }
}
