/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.bitspire.meetup.pulsar;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.impl.schema.JSONSchema;

public class App {

    public static void main(String[] args) {

        String url = "pulsar://localhost:6650";
        String topic = "persistent://public/default/schema-topic";

        try (PulsarClient client = PulsarClient.builder().serviceUrl(url).build()) {

            try (Producer<ChatMessage> producer = client.newProducer(JSONSchema.of(ChatMessage.class)).topic(topic).create()) {
                for (int i = 1; i <= 10; i++) {
                    String user = String.format("User-%02d", i);
                    producer.send(new ChatMessage(user, "Pulsar Rocks!"));
                }

            } catch (PulsarClientException e) {
                System.err.println("Cannot create producer");
                e.printStackTrace();
            }
        } catch (PulsarClientException e) {
            System.err.println("Cannot connect to Pulsar cluster");
            e.printStackTrace();
        }
    }
}
