/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.bitspire.meetup.pulsar;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.Schema;
import org.apache.pulsar.client.api.schema.SchemaBuilder;
import org.apache.pulsar.client.api.schema.GenericSchema;
import org.apache.pulsar.client.api.schema.GenericRecord;
import org.apache.pulsar.client.api.schema.RecordSchemaBuilder;
import org.apache.pulsar.common.schema.SchemaType;
import org.apache.pulsar.common.schema.SchemaInfo;

public class App {

    public static void main(String[] args) {

        String url = "pulsar://localhost:6650";
        String topic = "persistent://public/default/user-mysql-jdbc-sink-topic";
        // Can use Pojo class to create specific schema
        RecordSchemaBuilder recordSchemaBuilder = SchemaBuilder.record("User");
        recordSchemaBuilder.field("id").type(SchemaType.INT32);
        recordSchemaBuilder.field("age").type(SchemaType.INT32);
        recordSchemaBuilder.field("name").type(SchemaType.STRING);
        SchemaInfo schemaInfo = recordSchemaBuilder.build(SchemaType.AVRO);

        try (PulsarClient client = PulsarClient.builder().serviceUrl(url).build()) {
            GenericSchema schema = Schema.generic(schemaInfo);

            try (Producer<GenericRecord> producer = client.newProducer(schema).topic(topic).create()) {

                producer.newMessage()
                        .value(schema.newRecordBuilder().set("id", 1).set("age", 25).set("name", "User-01").build())
                        .send();

            } catch (PulsarClientException e) {
                System.err.println("Cannot create producer");
                e.printStackTrace();
            }
        } catch (PulsarClientException e) {
            System.err.println("Cannot connect to Pulsar cluster");
            e.printStackTrace();
        }
    }
}
