/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.bitspire.meetup.pulsar;

import java.util.Collection;
import java.util.function.Function;

/**
 * Simple function to sum the length of words within a window
 */
public class ProcessorFunction implements Function <Collection<String>, Integer> {
    @Override
    public Integer apply(Collection<String> words) {
        return words.stream().map(word -> word.length()).reduce(0, (x, y) -> x + y);
    }
}
